---
- name: Run macOS defaults.
  osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ osx_defaults }}"
  when: osx_use_defaults

- name: Run .osx dotfiles.
  shell: "{{ osx_script }}"
  changed_when: false
  when: osx_use_dotfile
